# Generated by Django 2.2 on 2019-04-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('tel', models.CharField(blank=True, max_length=19)),
                ('fax', models.CharField(blank=True, max_length=19)),
                ('address', models.TextField(blank=True)),
                ('insurance_code', models.TextField(blank=True, max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('child_benefit', models.DecimalField(decimal_places=2, max_digits=50)),
                ('dwelling_benefit', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Bon_benefit', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('number_of_employee', models.IntegerField()),
                ('decription', models.TextField(blank=True)),
                ('post_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseinfo.WorkStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('fathername', models.CharField(max_length=50)),
                ('national_code', models.CharField(max_length=10)),
                ('id_number', models.CharField(max_length=10)),
                ('insurance_id', models.CharField(max_length=10)),
                ('children_count', models.IntegerField()),
                ('tax_exempt', models.BooleanField(default=False)),
                ('indsurence_exempt', models.BooleanField(default=False)),
                ('tel', models.CharField(blank=True, max_length=19)),
                ('mobile', models.CharField(blank=True, max_length=19)),
                ('description', models.TextField(blank=True, null=True)),
                ('employee_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.EmployeeStatus')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.Employer')),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.MaritalStatus')),
                ('post_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.PostPlace')),
                ('work_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.WorkGroup')),
                ('work_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.WorkPlace')),
                ('work_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseinfo.WorkStatus')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.Bank')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Employee')),
            ],
        ),
    ]
