# Generated by Django 2.1.7 on 2019-04-10 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='title',
            field=models.CharField(max_length=50, verbose_name='نام بانک'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=30, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.Bank', verbose_name='نام بانک'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Employee', verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='children_count',
            field=models.IntegerField(verbose_name='تعداد فرزند'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.EmployeeStatus', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.Employer', verbose_name='کارفرما'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fathername',
            field=models.CharField(max_length=50, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(max_length=10, verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='indsurence_exempt',
            field=models.BooleanField(default=False, verbose_name='معافیت بیمه'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='insurance_id',
            field=models.CharField(max_length=10, verbose_name='کد بیمه'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.MaritalStatus', verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, max_length=19, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.PostPlace', verbose_name='محل پست'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_exempt',
            field=models.BooleanField(default=False, verbose_name='معافیت مالیاتی'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel',
            field=models.CharField(blank=True, max_length=19, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.WorkGroup', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.WorkPlace', verbose_name='محل کار'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseinfo.WorkStatus', verbose_name='وضعیت کاری'),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='title',
            field=models.CharField(max_length=50, verbose_name='وضعیت پرسنل'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='fax',
            field=models.CharField(blank=True, max_length=19, verbose_name='فکس'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='insurance_code',
            field=models.TextField(blank=True, max_length=20, verbose_name='کد کارگاهی'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='tel',
            field=models.CharField(blank=True, max_length=19, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='title',
            field=models.CharField(max_length=60, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='title',
            field=models.CharField(max_length=20, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='postplace',
            name='decription',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='postplace',
            name='number_of_employee',
            field=models.IntegerField(verbose_name='تعداد کارکنان '),
        ),
        migrations.AlterField(
            model_name='postplace',
            name='post_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseinfo.WorkStatus', verbose_name='وضعیت پست'),
        ),
        migrations.AlterField(
            model_name='postplace',
            name='title',
            field=models.CharField(max_length=60, verbose_name='محل پست'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='Bon_benefit',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='مبلغ بن'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='child_benefit',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='مبلغ حق اولاد'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='dwelling_benefit',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='مبلغ حق مسکن'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان گروه'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='title',
            field=models.CharField(max_length=60, verbose_name='محل کار'),
        ),
        migrations.AlterField(
            model_name='workstatus',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='workstatus',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان وضعیت شغلی'),
        ),
    ]
