# Generated by Django 2.1.7 on 2019-04-15 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0002_auto_20190410_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام شهر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='EducationDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='جنسیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryServiceStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='وضعیت نظام وظیفه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='سن'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_born',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_issu',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ صدور'),
        ),
        migrations.AddField(
            model_name='employee',
            name='experince_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سابقه کار'),
        ),
        migrations.AddField(
            model_name='employee',
            name='education_degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.EducationDegree', verbose_name='مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Gender', verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='employee',
            name='military_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.MilitaryServiceStat', verbose_name='وضعیت نظام وظیفه'),
        ),
        migrations.AddField(
            model_name='employee',
            name='place_of_born',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_of_born', to='baseinfo.City', verbose_name='محل تولد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='place_of_issu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_of_issu', to='baseinfo.City', verbose_name='محل صدور'),
        ),
    ]
