# Generated by Django 2.2 on 2019-04-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0004_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد ملی'),
        ),
    ]
