# Generated by Django 2.2 on 2019-04-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0006_auto_20190419_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='work_group',
            new_name='workgroup',
        ),
    ]
