# Generated by Django 2.2 on 2019-04-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0007_auto_20190421_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=1111, max_digits=50, verbose_name='پایه روزانه'),
            preserve_default=False,
        ),
    ]
