# Generated by Django 2.2 on 2019-04-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0008_workgroup_daily_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان ثابت')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='educationdegree',
            name='title',
            field=models.CharField(max_length=60, verbose_name='مدرک تحصیلی'),
        ),
    ]
