# Generated by Django 2.2 on 2019-04-03 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0009_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.Bank')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Employee')),
            ],
        ),
    ]
