# Generated by Django 2.2 on 2019-04-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0009_auto_20190422_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='constant',
            name='year',
            field=models.IntegerField(default=1397, verbose_name='سال'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
