# Generated by Django 2.2 on 2019-04-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0010_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
