# Generated by Django 2.2 on 2019-04-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo', '0001_initial'),
        ('wage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkdayStaus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseinfo.Employee')),
                ('wage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wage.Wage')),
                ('work_day_stat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.WorkdayStaus')),
            ],
        ),
    ]
