# Generated by Django 2.2 on 2019-04-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkdayStaus',
        ),
    ]
