# Generated by Django 2.2 on 2019-04-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_delete_workdaystaus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worksheet',
        ),
    ]
