# Generated by Django 2.2 on 2019-04-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_worksheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worksheet',
        ),
    ]
