# Generated by Django 2.2 on 2019-04-19 11:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo', '0006_auto_20190419_0525'),
        ('wage', '0007_auto_20190415_1650'),
        ('attendance', '0005_delete_worksheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_days_stat', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=31)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseinfo.Employee')),
                ('wage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wage.Wage')),
            ],
        ),
    ]
