# Generated by Django 2.2 on 2019-04-19 12:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_worksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='work_days_stat',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None),
        ),
    ]
