# Generated by Django 2.2 on 2019-04-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_shiftname'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftname',
            name='abbreviation',
            field=models.CharField(default='w', max_length=10),
            preserve_default=False,
        ),
    ]
