# Generated by Django 2.2 on 2019-04-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0007_auto_20190415_1650'),
        ('baseinfo', '0006_auto_20190419_0525'),
        ('attendance', '0010_shiftname_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftname',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='worksheet',
            unique_together={('wage', 'employee')},
        ),
    ]
