# Generated by Django 2.2 on 2019-04-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('is_locked', models.BooleanField()),
                ('pay_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wage.PayType')),
            ],
        ),
        migrations.CreateModel(
            name='WageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=5, max_digits=11)),
                ('tax_amount', models.DecimalField(decimal_places=5, max_digits=11)),
                ('insurance_amount', models.DecimalField(decimal_places=5, max_digits=11)),
                ('Loan_and_advance', models.DecimalField(decimal_places=5, max_digits=11)),
                ('deduction1', models.DecimalField(decimal_places=5, max_digits=11)),
                ('deduction2', models.DecimalField(decimal_places=5, max_digits=11)),
                ('net_pay', models.DecimalField(decimal_places=5, max_digits=11)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseinfo.Employee')),
                ('wage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wage.Wage')),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceAndLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=11)),
                ('description', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseinfo.Employee')),
            ],
        ),
    ]
