# Generated by Django 2.1.7 on 2019-04-10 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0001_initial'),
        ('wage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagedetail',
            name='absent_days',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='backpay_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='backpay_tax_exempt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='bad_wether_right',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='children_benefit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='commute_amont',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='daily_base',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='food_benefit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='hygiene_benefit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='instruct_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='insurance_include',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='is_shift',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='monthly_wage_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='ovettime_houre',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='pay_in_advance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='private_message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='public_message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='tax_include',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='tiemoff_days',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='work_as_replace',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='work_as_replace_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='work_days',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='work_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='baseinfo.WorkGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='work_in_friday_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='work_in_holiday_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='work_overtime_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='workdays_in_friday',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='workdays_in_holiday',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagedetail',
            name='workdays_in_mission',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='Loan_and_advance',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='deduction1',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='deduction2',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='gross_amount',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='net_pay',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
    ]
