# Generated by Django 2.1.7 on 2019-04-10 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0002_auto_20190410_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagedetail',
            name='wage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wage.Wage', verbose_name='نام لیست'),
        ),
    ]
