# Generated by Django 2.1.7 on 2019-04-10 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0003_auto_20190410_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagedetail',
            name='Loan_and_advance',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='وام و مساعده'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='absent_days',
            field=models.SmallIntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='backpay_amount',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='معوق مشمول'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='backpay_tax_exempt',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='معوق غیر مشمول'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='bad_wether_right',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='بدی آب و هوا'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='children_benefit',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='حق اولاد'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='commute_amont',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='مبلغ ایاب و ذهاب'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='daily_base',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='\u200dپایه روزانه'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='deduction1',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='سایر کسورات۱'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='deduction2',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='سایر کسورات ۲'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseinfo.Employee', verbose_name='نام ونام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='food_benefit',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='حق غذا'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='gross_amount',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='مبلغ ناخالص'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='hygiene_benefit',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='حق بهداشت'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='instruct_amount',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='مبلغ آموزش'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='مبلغ بیمه'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='insurance_include',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='مشمول بیمه'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='monthly_wage_amount',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='حقوق ماهیانه'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='net_pay',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='خالص پرداختی'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='ovettime_houre',
            field=models.DecimalField(decimal_places=3, max_digits=3, verbose_name='ساعت اضافه کاری'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='pay_in_advance',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='علی الحساب'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='private_message',
            field=models.TextField(verbose_name='پیام اختصاصی'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='public_message',
            field=models.TextField(verbose_name='پیام عمومی'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='مبلغ مالیات'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='tax_include',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='مشمول مالیات'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='tiemoff_days',
            field=models.SmallIntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='work_as_replace',
            field=models.SmallIntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='work_as_replace_amount',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='مبلغ جایگزینی'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='work_days',
            field=models.SmallIntegerField(verbose_name='تعداد روز کارکرد'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='work_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseinfo.WorkGroup', verbose_name='گروه شغلی'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='work_in_friday_amount',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='مبلغ جمعه کاری'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='work_in_holiday_amount',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='مبلغ تعطیل کاری'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='work_overtime_amount',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='مبلغ اضافه کاری'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='workdays_in_friday',
            field=models.SmallIntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='workdays_in_holiday',
            field=models.SmallIntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='workdays_in_mission',
            field=models.SmallIntegerField(verbose_name=''),
        ),
    ]
