# Generated by Django 2.1.7 on 2019-04-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0004_auto_20190410_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagedetail',
            name='shift_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11, verbose_name='مبلغ نوبتکاری'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='absent_days',
            field=models.SmallIntegerField(verbose_name='روز غیبت'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='is_shift',
            field=models.BooleanField(default=True, verbose_name='وضعیت نوبتکاری'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='tiemoff_days',
            field=models.SmallIntegerField(verbose_name='روز مرخصی'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='work_as_replace',
            field=models.SmallIntegerField(verbose_name='جایگزینی'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='workdays_in_friday',
            field=models.SmallIntegerField(verbose_name='جمعه کاری'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='workdays_in_holiday',
            field=models.SmallIntegerField(verbose_name='تعطیل کاری'),
        ),
        migrations.AlterField(
            model_name='wagedetail',
            name='workdays_in_mission',
            field=models.SmallIntegerField(verbose_name='ماموریت'),
        ),
    ]
