# Generated by Django 2.2 on 2019-04-20 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0006_auto_20190419_0525'),
        ('wage', '0007_auto_20190415_1650'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wagedetail',
            unique_together={('wage', 'employee')},
        ),
    ]
