# Generated by Django 2.2 on 2019-04-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0006_auto_20190419_0525'),
        ('wage', '0008_auto_20190420_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='wage',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='baseinfo.Employer', verbose_name='شرکت'),
            preserve_default=False,
        ),
    ]
