# Generated by Django 2.2 on 2019-04-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0009_wage_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wagedetail',
            old_name='work_group',
            new_name='workgroup',
        ),
    ]
