# Generated by Django 2.2 on 2019-04-22 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0010_auto_20190421_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wagedetail',
            name='workgroup',
        ),
    ]
