# Generated by Django 2.2 on 2019-04-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0011_remove_wagedetail_workgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='wage',
            name='total_23per_insur_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wage',
            name='total_7per_insur_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wage',
            name='total_absents',
            field=models.IntegerField(default=0, verbose_name='جمع روزهای غیبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wage',
            name='total_dayoffs',
            field=models.IntegerField(default=0, verbose_name='جمع روزهای مرخصی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wage',
            name='total_employees',
            field=models.IntegerField(default=0, verbose_name='تعداد کارکنان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wage',
            name='total_gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='جمع ناخالص'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wage',
            name='total_insuracne_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wage',
            name='total_net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wage',
            name='total_overtime',
            field=models.IntegerField(default=0, verbose_name='جمع ساعت اضافه کاری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wage',
            name='total_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wage',
            name='total_tax_included_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wage',
            name='total_workdays',
            field=models.IntegerField(default=0, verbose_name='تعداد روزهای کاری'),
            preserve_default=False,
        ),
    ]
